version: '3'

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        env_file: amq.env
        ports:
            - '5672:5672'
            - '15672:15672'
    scheduler-ci:
        image: scheduler-ci
        container_name: scheduler-ci
        env_file: scheduler-ci.env
        ports:
        - 5000:5000
    mongo:
        #Production mode
        #see https://www.surenderthakran.com/articles/tech/production-mongodb-using-docker
        image: mongo
        container_name: MongoDb
        env_file: mongo.env
        volumes:
            - /volumes/mongo:/data/db
        ports:
            - '27017-27019:27017-27019'