name: ESGI Micro CI Scheduler

on: [push, pull_request]

jobs:
  build:
    name: Build Micro CI Scheduler Project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v1

    - name: Setup Python 3.7 environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install dependencies
      run: pip install -r requirements.txt && pip install 'pymongo[srv]' && pip install flake8

    - name: Launch linter
      run: flake8

    - name: launch Unit Test
      run: python -m unittest discover

    # Add your build steps here

    #setup an environnement python 3.7
    #install dependences

  # Uncomment and replace {userName} by your account folder name
  # deploy:
  #   name: Build/Publish Docker Images to DockerHub & Deploy to Azure VM
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/master'

  #   steps:
  #   - name: Checkout Project
  #     uses: actions/checkout@v1

  #   - name: Build & Publish Docker Image
  #     uses: docker/build-push-action@v1
  #     with:
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}
  #       repository: micro-ci-al1/micro-ci-scheduler
  #       tag_with_ref: true

  #   - name: Azure Login
  #     uses: azure/login@v1
  #     with:
  #       creds: ${{ secrets.AZURE_CREDENTIALS }}

  #   - name: Azure CLI script
  #     uses: azure/CLI@v1
  #     with:
  #       inlineScript: |
  #         az vm run-command invoke -g ${{ secrets.AZURE_RESOURCE_GRP }} -n ${{ secrets.AZURE_VM }} --command-id RunShellScript --scripts "cd /home/{userName} && wget -q https://raw.githubusercontent.com/esgi-microservices-al1/micro-ci-scheduler/master/.github/azure/docker-compose.yml -O docker-compose.yml && docker-compose stop && docker-compose rm && docker-compose up -d"